<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Quiz;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends EntityRepository {

    public function findQueryForAll() {
        $qb = $this->createQueryBuilder('req');
        $query = $qb->add('select', 'a')->add('from', 'AppBundle:Quiz a')->getQuery();

        return $query;
    }

    private function isAWordInASentence($sentence, $word) {
        if (strripos($sentence, $word) !== false) {
            return TRUE;
        } else {
            return FALSE;
        }
    }

    public function getQuizBySegment($segment) {
        $allQuizz = $this->findAll();

        $selectedQuiz = [];
        foreach ($allQuizz as $quiz) {
            if ($this->isAWordInASentence($quiz->getNom(), $segment) === TRUE)
                $selectedQuiz[] = $quiz;
        }
        return $selectedQuiz;
    }

}
